@base_url = http://localhost:8080/api

###
# === AUTH CONTROLLER===
###

### LOGIN - Admin account (Happy Path)
POST {{base_url}}/auth/login
Content-Type: application/json

{
  "email": "admin@umbc.com",
  "password": "P@ssw0rd!"
}

### After this request, copy the token from the response and assign it below:
# @admin_token = Bearer <PASTE_ADMIN_JWT_HERE>
@admin_token = Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJyZXRyaWV2ZXItZXNzZW50aWFscyIsInN1YiI6ImFkbWluQHVtYmMuY29tIiwiYXBwVXNlcklkIjoxLCJyb2xlIjoiUk9MRV9BRE1JTiIsImV4cCI6MTc0NjYyMDMzOX0.yi1YsjGKuiFbk2bNnUAPPR2IYKNhBmte1RHRYK9Fi_Q

### LOGIN - Authority1 account (Happy Path)
POST {{base_url}}/auth/login
Content-Type: application/json

{
  "email": "authority1@umbc.com",
  "password": "P@ssw0rd!"
}

### @auth1_token = Bearer <PASTE_AUTHORITY1_JWT_HERE>
@auth1_token = Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJyZXRyaWV2ZXItZXNzZW50aWFscyIsInN1YiI6ImF1dGhvcml0eTFAdW1iYy5jb20iLCJhcHBVc2VySWQiOjIsInJvbGUiOiJST0xFX0FVVEhPUklUWSIsImV4cCI6MTc0NjMzNDg2OX0.ZCu8ND48uA0qCq3WYpiIW_jBdnCJhyWfOx2hsxUPukE


### LOGIN - Invalid password (Sad Path)
POST {{base_url}}/auth/login
Content-Type: application/json

{
  "email": "admin@umbc.com",
  "password": "WrongPassword"
}


### REFRESH TOKEN - Admin (Happy Path)
POST {{base_url}}/auth/refresh
Authorization: {{admin_token}}


### REFRESH TOKEN - Invalid / Expired (Sad Path)
POST {{base_url}}/auth/refresh
Authorization: Bearer invalid.token.value


###
# === APP USER CONTROLLER ===
###

### GET ALL USERS - Admin (Happy Path)
GET {{base_url}}/user
Authorization: {{admin_token}}


### GET USER BY ID - Admin (Happy Path)
GET {{base_url}}/user/1
Authorization: {{admin_token}}

### GET USER BY ID - Authority (Happy Path)
GET {{base_url}}/user/2
Authorization: {{auth1_token}}

### GET USER BY ID - Not Found
GET {{base_url}}/user/999
Authorization: {{admin_token}}

### GET USER BY EMAIL - Admin (Happy Path)
GET {{base_url}}/user/email/admin@umbc.com
Authorization: {{admin_token}}

### GET USER BY EMAIL - Admin (Not Found)
GET {{base_url}}/user/email/not@found.com
Authorization: {{admin_token}}

### POST ADD USER - Admin (Happy Path)
POST {{base_url}}/user
Content-Type: application/json
Authorization: {{admin_token}}

{
  "username": "test@admin.com",
  "password": "P@ssw0rd!",
  "userRole": "ADMIN"

}

### PUT CHANGE PASSWORD - Admin (Happy Path)
PUT {{base_url}}/user/password
Content-Type: application/json
Authorization: {{admin_token}}

{
  "password": "newSecureP@ss123"
}

### PUT CHANGE PASSWORD - Missing password field (Sad Path)
PUT {{base_url}}/user/password
Content-Type: application/json
Authorization: {{admin_token}}

{
  "pass": "nope"
}


### PUT ENABLE USER BY ID - Admin
PUT {{base_url}}/user/enable/2
Authorization: {{admin_token}}


### PUT DISABLE USER BY ID - Admin
PUT {{base_url}}/user/disable/2
Authorization: {{admin_token}}


### PUT ENABLE USER - Not Found (Sad Path)
PUT {{base_url}}/user/enable/999
Authorization: {{admin_token}}


### PUT DISABLE USER - Not Found (Sad Path)
PUT {{base_url}}/user/disable/999
Authorization: {{admin_token}}
